name: effects-a-la-carte
version: 0.1.0.0
synopsis: Effects a la carte
license: BSD3
author: Mitchell Rosen
maintainer: mitchellwrosen@gmail.com
github: mitchellwrosen/effects-a-la-carte
copyright: 2016 Mitchell Rosen
category: Control

default-extensions:
  - BangPatterns
  - DataKinds
  - DeriveFunctor
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - TypeOperators

library:
  source-dirs: src
  dependencies:
    - base
    - concurrent-supply
    - transformers
  other-modules: []
